### PR TITLE
Adding documentation for `dotstars` attribute.

### PR DESCRIPTION
**Pull request by davegoopot**
I couldn't figure out how the API docs were generated and sent to https://circuitpython.readthedocs.io/projects/funhouse/en/latest/api.html#adafruit-funhouse-peripherals and so I've not been able to test this formats OK.

If someone could give me a pointer on how to run a test build of the API doc, I'd be happy to give it a test.

### CODE REVIEW

**Comment by makermelissa** [comment]
Thanks for submitting this. It looks like the error is not in this library, but in adafruit_requests:
```
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/adafruit_requests.py", line 114, in Response
    def __init__(self, sock: SocketType, session: Optional["Session"] = None) -> None:
NameError: name 'SocketType' is not defined

Error: Process completed with exit code 2.
```

**Comment by makermelissa** [comment]
Looks like the failure is related to issue https://github.com/adafruit/Adafruit_CircuitPython_Requests/pull/93. I'd like to wait for it to be fixed before we merge this in, so we can re-run and have it pass cleanly.

**Comment by makermelissa** [comment]
This keeps installing Adafruit_CircuitPython_Requests 1.10.4 which has the bug and is not updating to 1.10.5. I am going to close this and re-open in an attempt to have it update.

**Comment by makermelissa** [comment]
I forced it to install the latest version by specifying it in the dependencies, but it refuses to work:
```
ERROR: Could not find a version that satisfies the requirement adafruit-circuitpython-requests>=1.10.5 (from versions: 1.1.4, 1.1.5, 1.2.0, 1.3.0, 1.4.0, 1.4.1, 1.4.2, 1.4.3, 1.5.0, 1.6.0, 1.7.0, 1.7.1, 1.7.2, 1.7.3, 1.7.4, 1.7.5, 1.8.0, 1.8.1, 1.9.0, 1.9.1, 1.9.2, 1.9.3, 1.9.4, 1.9.5, 1.9.6, 1.9.7, 1.9.8, 1.9.9, 1.10.0, 1.10.1, 1.10.2, 1.10.3, 1.10.4)
ERROR: No matching distribution found for adafruit-circuitpython-requests>=1.10.5
```

I can run it locally on my computer, so it seems to cache older versions of the available dependencies. I'll have to circle back to this later. Maybe by then the cache will have expired and it will have an update.

**Comment by kevincon** [comment]
I think that may be due to the 1.10.5 version of adafruit_requests now requiring Python 3.8 while this library's CI is setup to use Python 3.7, so pip doesn't consider the 1.10.5 version of adafruit_requests as a candidate for installation under Python 3.7.

**Comment by makermelissa** [comment]
> I think that may be due to the 1.10.5 version of adafruit_requests now requiring Python 3.8 while this library's CI is setup to use Python 3.7, so pip doesn't consider the 1.10.5 version of adafruit_requests as a candidate for installation under Python 3.7.

Thank you. That's a good theory and makes sense.

**Comment by makermelissa** [comment]
It appears the remote repository is not allowing me to push changes anymore, so I'm closing and will open my own PR.

**Pull request closed without merging**
