### PR TITLE
Convenience method to set all the dotstars to the same color 

### PR DESCRIPTION
**Pull request by davegoopot**

### CODE REVIEW

**Comment by davegoopot** [comment]
Hello, I don't know how to get past the build docs failure. Any advice greatly appreciated.

**Comment by makermelissa** [comment]
Hi, this function is already built into the `dotstars` object. So to set them all to 0x00FF00 for instance, you can actually just call:
```
from adafruit_funhouse import peripherals

peripherals = Peripherals()
peripherals.dotstars.fill(0x00FF00)
```

**Comment by makermelissa** [comment]
Thanks for adding this, but I'm going to close this because it adds duplicate functionality and these libraries are pretty close to pushing the memory limit over the line.

**Comment by davegoopot** [comment]
Thanks for the update. I'll have a go submitting a different PR to add the `dotstar` attribute to the Sphinx docs if that's OK.

**Comment by makermelissa** [comment]
Yep, thank you.

**Pull request closed without merging**
